### ISSUE TITLE
Use ".h" suffix for header files

### ISSUE THREAD

**Issue by tkem** [tkem/fsmlite#12]
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rs-file-suffix

**Comment by tkem** [comment]
Well your C compiler wouldn't like fsmlite if you wrote `#include <fsmlite.hpp>` in a C program either, so that's irrelevant.
Though it might be debatable, I decided to follow the Core Guidelines unless there's really good reason not to - which in this case, I think there's not.

**Comment by degski** [comment]
"Well your C compiler wouldn't like fsmlite if you wrote #include <fsmlite.hpp> in a C program either, so that's irrelevant."

If the header has the extension .hpp, I wouldn't try to include it in a C-source file (that's the relevance), because it screams at me that it's a C++ header.

**Comment by tkem** [comment]
As it states, "it’s easier to name all headers .h instead of having different extensions for just those headers that are intended to be shared with C".
Anyway, this issue is closed - you're flogging a dead horse.
