### ISSUE TITLE
time complxity of this fsm

### ISSUE THREAD

**Issue by choxsword** [tkem/fsmlite#16]
I aprreciate the code you shared. But  it seems that every time this fsm handles an event,  it needs to search the transition table. So **the time complexity for each call of `process_event` is O(N)** (N is the count of rows) , not O(1), which makes this fsm unpractical .

**Comment by tkem** [comment]
For time complexity etc. see the references given in the README.

**Comment by choxsword** [comment]
sorry but i can't find the references in README. I only found a documentation of api.

**Comment by choxsword** [comment]
I look through the linkage of **MSM** but still not found anything explicitly about **time complexity**. Is there anything wrong with my analysis of **O(N) complexity** above?
