### ISSUE TITLE
How to use std::shared_ptr as a trigger event in the state transition table

### ISSUE THREAD

**Issue by yabbasi31415** [tkem/fsmlite#25]
In the examples given in fsmlite/tests/, replacing the event data type with an event-type std::shared_ptr gives the following error

`fsm.h:140:106: error: call of overloaded ‘forward<const std::shared_ptr<event>&>(const std::shared_ptr<event>&)’ is ambiguous
             return binary_fn_helper<F, Arg1, Arg2>::invoke(forward<F>(f), forward<Arg1>(a), forward<Arg2>(b));`

**Comment by tkem** [comment]
@yabbasi31415: What platform/compiler are you using?

**Comment by yabbasi31415** [comment]
@tkem I'm using g++ compiler (version 7.5.0) on Linux

**Comment by tkem** [comment]
@yabbasi31415 Thanks for reporting! This should be fixed in https://github.com/tkem/fsmlite/tree/fix/25

**Comment by tkem** [comment]
Fixed in v0.7.3.
